#!/usr/bin/lua
local debug=require"vserver.debug"
debug:setverbose(4)
local phase,vserver=table.unpack(arg)
--[[
	prepre-start)
	pre-start)
	post-stop)
]]
local nc=require"vserver.netconfig"
local ns=require"vserver.netip"
local phases={}

local config=nc.configload()
local function baseif(v)
	local baseintf="vlan"..v.vid
	if not ns.intfexists(baseintf) then
		ns.createvlan(config.masteriface,baseintf,v.vid)
	end
end
local function mvlan(n,v)
	local baseintf="vlan"..v.vid
	ns.createmvlan(baseintf,n,v.mac)
end
local function tmpname(v)
	return string.sub("t-"..v.vid.."-"..vserver,1,15)
end

phases["prepre-start"]=function ()
	for k,v in pairs(config.network[vserver]) do
		debug:debug(2,"creating ",k,"\n")
		local tname=tmpname(v)
		baseif(v)
		mvlan(tname,v)
		ns.ifsetns(vserver,tname,k)
	end
end
phases["pre-start"]=function()
	local configureipv6lo
	for k,v in pairs(config.network[vserver]) do
		debug:debug(2,"configuring ",k,"\n")
		if v.ip6 ~= nil then
			configureipv6lo=1
			local sc="net/ipv6/conf/"..k
			ns.sysctl(vserver,sc,"disable_ipv6",0)
			if v.ip6 ~= "radvd" then
				ns.sysctl(vserver,sc,"autoconf",0)
				ns.ipns(vserver,"ip addr add dev",k,v.ip6)
			end
			if v.ip6gw ~= nil then
				ns.sysctl(vserver,sc,"router_solicitations",0)
				ns.sysctl(vserver,sc,"dad_transmits",0)
				ns.sysctl(vserver,sc,"accept_dad",0)
				ns.sysctl(vserver,sc,"accept_ra",0)
			end
		end
		ns.ipns(vserver,"ip addr add dev",k,v.ip)
	end
	if configureipv6lo then
		ns.sysctl(vserver,"net/ipv6/conf/lo","disable_ipv6",0)
	end
	for k,v in pairs(config.network[vserver]) do
		debug:debug(2,"configuring ",k,"\n")
		if not v.noup then
			ns.ipns(vserver,"ip link set up dev",k)
		end
	end
	for k,v in pairs(config.network[vserver]) do
		debug:debug(2,"configuring ",k,"\n")
		if v.unreachable then
			for _,route in pairs(v.unreachable) do
				ns.ipns(vserver,"ip ro add unreachable",route)
			end
    end
		if v.gw then
			ns.ipns(vserver,"ip ro add default via",v.gw,"dev",k)
		end
		if v.ip6gw ~= nil and v.ip6gw ~= "none" then
			ns.ipns(vserver,"ip ro add default via",v.ip6gw,"dev",k)
		end
	end
end
phases["post-stop"]=function()
	for k,v in pairs(config.network[vserver]) do
		debug:debug(2,"removing ",k,"\n")
		ns.ipns(vserver,"ip link set down dev",k)
		ns.ipns(vserver,"ip link del",k)
	end
end

if phases[phase] then
	phases[phase]()
else
	debug:debug(0,"arguments not understood")
end

