#!/bin/sh -e

if [ "$1" = configure ]; then
	if [ -s /root/preload/vserver/build-template.sh -o -s /root/preload/vserver/build-vserver.sh ]; then
		echo "verwijderen oude build-*.sh scripts"
		rm -f /root/preload/vserver/build-template.sh /root/preload/vserver/build-vserver.sh
	fi
	if [ -d /root/preload ]; then
		if [ -d /root/preload.OUD ]; then
			echo 'Er bestaat een /root/preload en /root/preload.OUD; beiden verwijderen AUB!'
		else
			mv /root/preload /root/preload.OUD
			echo 'oude /root/preload/ dir naar preload.OUD/ verplaatst; AUB handmatig verwijderen'
		fi
	fi
	mountpoint=`df -P /var/lib/vservers/. | awk '/\\// {print $1}'`
	if [ -z "$mountpoint" ]; then
		echo
		echo '*** Kan mountpoint van vservers niet bepalen!'
		echo '*** Controleer zelf of tag,notagcheck mount options actief zijn'
		echo
		sleep 3
		exit 0
	fi
	if ! grep "^$mountpoint\>" /etc/fstab >/dev/null; then
		case "$mountpoint" in
			/dev/mapper/*)	# verbouw /dev/mapper/main-vservers naar /dev/main/vservers
					mountpoint=/dev/`echo ${mountpoint#/dev/mapper/} | sed 's,\([^-]\)-\([^-]\),\1/\2,; s,--,-,'`;;
			*)		;;
		esac
	fi
	set -- `grep "^$mountpoint\>" /etc/fstab`
	if [ $# -ne 6 ]; then
		echo
		echo '*** Kan mountpoint van vservers niet bepalen!'
		echo '*** Controleer zelf of tag,notagcheck mount options actief zijn'
		echo
		sleep 3
		exit 0
	fi
	case "$4" in
		*tag,notagcheck*)	echo "mount options van $mountpoint zijn OK";;
		*)
			echo "$mountpoint mount options fixen"
			perl -i.bak -pe "if (m:^$mountpoint\s:)"' { print "#tag " . $_; s:^(\S+\s+\S+\s+\S+\s+)\S+\s+:${1}tag,notagcheck\t:;}' /etc/fstab
			diff -u /etc/fstab.bak /etc/fstab | grep "$mountpoint" || true
			echo
			echo '*** Een reboot is nog wel nodig om dit te activeren! ***'
			echo
			sleep 2
	esac

	# Zet default fstab neer zonder /tmp
	cat > /etc/vservers/.defaults/fstab <<EOT
none	/proc		proc	defaults		0 0
none	/dev/pts	devpts	gid=5,mode=620		0 0
EOT
	# Fix meteen alle symlinks
	/usr/local/sbin/fix-vservers
	
fi
