#!/bin/sh -e

if [ "$1" = remove -o "$1" = purge ]; then
	if mount | awk '/ \/var / {print $6}' | grep 'tag,notagcheck' >/dev/null; then
		echo
		echo "Let op!  /var is nog geconfigureerd met tag,notagcheck options."
		echo "         Dit wil je mogelijk aanpassen..."
		echo
		sleep 2
	fi
fi
