#!/usr/bin/lua
local vsd=require("vserver.debug")
vsd:setverbose(1)
local vserver=require("vserver.vserver")
local script=require("vserver.scripts")
local pa=require("vserver.args")

local vservers=vserver.list()
local scripts=script.list()

local oldversion=vserver.oldversion()

local options = {}
function options._quiet(d,cb)
	vsd:setverbose(0)
	return 0,nil
end

function options._debug(d,cb)
	vsd:setverbose(tonumber(cb:nextarg()))
	return 0,nil
end


pa.parseargs(arg,options,{})

-- main: voer uit voor alle vservers:
for _,aVserver in pairs(vservers) do
	vsd:debug(1,aVserver:name(),":")
	aVserver:deploy_scripts(scripts)
	aVserver:fix_dependency()
	vsd:debug(1,"\n")
end
